spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/pki_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

pki:
  cdp:
    url: ${PKI_CDP_URL:http://localhost:8080/api/v1/crl}
  aia:
    ocsp-url: ${PKI_OCSP_URL:http://localhost:8080/api/v1/ocsp}
    ca-issuer-base-url: ${PKI_CA_ISSUER_URL:http://localhost:8080/api/v1/certificates/}
